### PR TITLE
Comprehensively improve the translation of Simplified Chinese, and supplement the help document about three ways to use add-on.

### PR DESCRIPTION
**Pull request by cary-rowen**
Hello,

Simplified Chinese documents used to be machine translated, now they are easier to understand.
About the "Using" section in readme.md
We should update, now the add-on has three methods to translate text.
I changed it, please check it out.

Thanks.

### CODE REVIEW

**Comment by CyrilleB79** [comment]
Hello @cary-rowen 
Translations were usually sent throught SVN translation system. I did not understand clearly if the workflow is still working as expected today.
In case Simplified Chinese translations should be sent through SVN system and this PR closed, I have taken your suggestion for the main readme in #8 including other doc fixes/updates. I hope you don't mind.

**Comment by cary-rowen** [comment]
@CyrilleB79 
Hello,

Thank you for your kind reminder,
I will submit a new translation through SVN, but I have a question. Will the readme in Simplified Chinese also be extracted from SVN?

have a nice weekend.

**Comment by CyrilleB79** [comment]
In the workflow based on the SVN repo, the documentation of the add-on were taken from the website documentation, i.e. :
1. The add-on author (or someone else for him/her) put the English readme (slightly modified) as a .mdwn file in the SVN website folder
2. A .po is generated automatically from the English README
3. Translators translate this .po in all languages; if you are not member of the translation team for your language, you may want ask them to include you
4. The translated community website page (html) for this add-on is automatically generated from your translated .po
5. The thml file is also automatically included to the add-on's stable branch with other translations.

@beqabeqa473 is the step 5. still working for Instant Translate? Thanks.

**Comment by cary-rowen** [comment]
Hello,

I will close this PR. Thanks again for your answers.
I will update this part of the translation in the SVN repository and wait for @beqabeqa473 to release a new version.

Thanks.

**Pull request closed without merging**
