### PR TITLE
Added the ability to translate the last spoken text

### PR DESCRIPTION
**Pull request by grisov**
Added a new feature.
By pressing L in the add-on layer mode you can get a translation of the last spoken text.

### CODE REVIEW

**Comment by cary-rowen** [comment]
Hope to merge this PR

**Comment by cary-rowen** [comment]
@beqabeqa473

**Comment by beqabeqa473** [comment]
Hello.

Sorry for delay of merging this pr.

i have several showstoppers to merge this.

1. for what reason version was changed in such way?
2. what is the reason of checking version support and doing equality check for nvda 2021 in speech functions? i ttested and everything works as it worked before, so i think there is no need to check that.

**Comment by grisov** [comment]
Hi Beqa,

Sorry for the version - I built the add-on and forgot return the previous value after.

I have corrected this shortcoming here d5f0e5de368d2f .

Regarding the speech module.

The fact is that in NVDA 2021.1 the speak() function was transferred from the file ``speech\__init__.py`` to ``speech\speech.py``.

For this reason, the translation function of the last spoken text has stopped working in new NVDA.

So I solved this question this way, but we can think of other solutions.

**Comment by beqabeqa473** [comment]
ok, i tested and yes, it works this way.



On 5/27/21, Oleksandr Gryshchenko ***@***.***> wrote:
> Hi Beqa,
>
> Sorry for the version - I built the add-on and forgot return the previous
> value after.
>
> I have corrected this shortcoming here d5f0e5de368d2f .
>
> Regarding the speech module.
>
> The fact is that in NVDA 2021.1 the speak() function was transferred from
> the file ``speech\__init__.py`` to ``speech\speech.py``.
>
> For this reason, the translation function of the last spoken text has
> stopped working in new NVDA.
>
> So I solved this question this way, but we can think of other solutions.
>
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/beqabeqa473/instantTranslate/pull/1#issuecomment-849785747


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by cary-rowen** [comment]
Maybe we should also update the help in "readme.md".

**Comment by grisov** [comment]
Hi Cary and Beqa,  

Beqa, if you don't mind, i can add information to the readme and help message on this weekend.  

Have a nice day!  

Oleksandr

**Comment by grisov** [comment]
Updated ReadMe and add-on messages here #5 .

**Pull request merged**
